# Numpy Basic Concepts
<img src="../img/numpy.png" alt="guido"  height="150" align="left"> 

## 1 What is Numpy ?

NumPy is the fundamental package for scientific computing with Python. It is:

* a powerful Python extension for N-dimensional array
* a tool for integrating C/C++ and Fortran code
* designed for scientific computation: linear algebra and Signal Analysis

## 2 Array Creation

The most important attributes of an ndarray object are:

* **ndarray.ndim**     - the number of axes (dimensions) of the array. 
* **ndarray.shape**    - the dimensions of the array. For a matrix with n rows and m columns, shape will be (n,m). 
* **ndarray.size**     - the total number of elements of the array. 
* **ndarray.dtype**    - numpy.int32, numpy.int16, and numpy.float64 are some examples. 
* **ndarray.itemsize** - the size in bytes of elements of the array. For example, elements of type float64 has itemsize 8 (=64/8) 

In [116]:
a = np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11]])
rows, cols = np.shape(a)
print a
print 'Rows:{0:03d} ; Cols:{0:03d}'.format(rows, cols)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Rows:003 ; Cols:003


In [117]:
print a
print 'ndim',a.ndim         # Number of dimensions
print 'dtype',a.dtype.name  # Type of data
print 'itemsize in bytes',a.itemsize # Size in bytes of elements
print 'size',a.size         # Number of elements in the array

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
ndim 2
dtype int32
itemsize in bytes 4
size 12


In [118]:
b = np.array([[2,3], [6,7]], dtype=np.complex64)
print b

[[ 2.+0.j  3.+0.j]
 [ 6.+0.j  7.+0.j]]


### 2.1 Array creation functions

Often, the elements of an array are originally unknown, but its size is known. Hence, **NumPy** offers several functions to create arrays with initial placeholder content.

The function `zeros` creates an array full of zeros, the function `ones` creates an array full of ones, and the function `empty` creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64.  

In [119]:
print zeros((3,4))
print '-'*80

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
--------------------------------------------------------------------------------


In [120]:
print ones((3,4))
print '-'*80

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
--------------------------------------------------------------------------------


In [121]:
print empty((2,3))
print '-'*80

[[  2.12199579e-314   6.36598737e-314   1.06099790e-313]
 [  1.48539705e-313   1.90979621e-313   2.33419537e-313]]
--------------------------------------------------------------------------------


In [122]:
print eye(3)
print '-'*80

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
--------------------------------------------------------------------------------


In [123]:
print diag(np.arange(5))
print '-'*80

[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]
--------------------------------------------------------------------------------


In [124]:
print np.tile(np.array([[6, 7], [8, 9]]), (2, 2))

[[6 7 6 7]
 [8 9 8 9]
 [6 7 6 7]
 [8 9 8 9]]


In [142]:
print b
print '-'*40
print np.zeros_like(b)


[ 1.  2.  2.  2.  4.  4.]
----------------------------------------
[ 0.  0.  0.  0.  0.  0.]


### 2.2 Sequences and reshaping

Arrays can be created with ***linspace***, ***logspace*** (returning evenly spaced numbers, linear or logarithmic) or ***arange*** and then shaped in matrix form. **mgrid** is like the equivaled "meshgrid" in MATLAB.

In [126]:
x = np.arange(4).reshape(2,2)
print x

[[0 1]
 [2 3]]


In [127]:
# Use List comprehention to create a matrix
c = np.array([[10*j+i for i in range(3)] for j in range(4)])
print c

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [128]:
X, Y = np.mgrid[0:5, 0:5] # similar to meshgrid in MATLAB
X

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [129]:
Y

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

### 2.3 Sparse Matrices

We can create and manipulate sparse matrices as follows:

In [143]:
from scipy import sparse
X = np.random.random((5, 3)) # Create an array with many zeros
X[X < 0.85] = 0
print X
print '-'*80
X_csr = sparse.csr_matrix(X) # turn X into a csr (Compressed-Sparse-Row) matrix
print X_csr

[[ 0.          0.          0.93035439]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.88050273  0.        ]
 [ 0.95987337  0.          0.        ]]
--------------------------------------------------------------------------------
  (0, 2)	0.930354389604
  (3, 1)	0.880502725183
  (4, 0)	0.959873365105


In [131]:
print X_csr.toarray()       # convert back to a dense array

[[ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.96745262  0.          0.        ]
 [ 0.          0.85022281  0.        ]
 [ 0.          0.          0.99267928]]


### 2.4 Random Numbers

In [132]:
np.random.rand(5,3) # uniform random numbers in [0,1]

array([[ 0.31832742,  0.37608291,  0.99055753],
       [ 0.80288212,  0.27763634,  0.94914471],
       [ 0.43359204,  0.23856717,  0.21959412],
       [ 0.83663348,  0.57039126,  0.63852362],
       [ 0.82770992,  0.68977332,  0.03625068]])

### 2.5 Casting
Forced casts:

In [133]:
a = np.array([1.7, 1.2, 1.6])
b = a.astype(int)           # <-- truncates to integer
b

array([1, 1, 1])

Rounding:

In [134]:
a = np.array([1.2, 1.5, 1.6, 2.5, 3.5, 4.5])
b = np.around(a)
print b                     # still floating-point
c = np.around(a).astype(int)
print c

[ 1.  2.  2.  2.  4.  4.]
[1 2 2 2 4 4]


## 4 Basic Linear Algebra

In [135]:
# Transpose
print x
print '-'*50
print x.T

[[0 1]
 [2 3]]
--------------------------------------------------
[[0 2]
 [1 3]]


In [136]:
print x
x.min()

[[0 1]
 [2 3]]


0

In [137]:
print x
print x*5         # Scalar expansion

[[0 1]
 [2 3]]
[[ 0  5]
 [10 15]]


In [138]:
print x
print x+3

[[0 1]
 [2 3]]
[[3 4]
 [5 6]]


In [144]:
print x*x.T       # Elementwise product
print '-'*40
print np.dot(x,x.T)  # Dot (matrix) product

[[0 2]
 [2 9]]
----------------------------------------
[[ 1  3]
 [ 3 13]]


### 4.1 Determinant of a square matrix
The `scipy.linalg.det()` function computes the determinant of a square matrix:

In [146]:
from scipy import linalg
arr = np.array([[1, 2],
               [3, 4]])
print arr
print '-'*40
print linalg.det(arr)

[[1 2]
 [3 4]]
----------------------------------------
-2.0


### 4.2 Inverse of a square matrix
The `scipy.linalg.inv()` function computes the inverse of a square matrix:

In [141]:
print arr
print '-'*40
print linalg.inv(arr)

[[1 2]
 [3 4]]
----------------------------------------
[[-2.   1. ]
 [ 1.5 -0.5]]


end...